const actions = {
	CHANGE_VALUE: 'CHANGE_VALUE',
	GET_WEATHER: 'GET_WEATHER',
	SET_WEATHER_PICKED: 'SET_WEATHER_PICKED',
	GET_CITIS_SEARCH: 'GET_CITIS_SEARCH',
	SEARCH_WEATHER: 'SEARCH_WEATHER',
};

export default actions;
